### ISSUE TITLE
Bad call form

### ISSUE THREAD

**Issue by 2mac** [deavmi/Gitsy#7]
Your use of `call` is not only sloppy, it would not execute. Please test code before committing.

**Comment by deavmi** [comment]
Okay. Will do.

**Comment by deavmi** [comment]
Working on it now.

P.S Is a list created like this...


````Python
h = ["echo", "hi", ">", "h.text"]
print(h[2]
````

That should print `>`?

**Comment by 2mac** [comment]
No. You can't use BASH syntax in a `call()` unless you are calling BASH. The first in the array is the program, and the rest is its `argv`. To direct output to a file, use `call()`'s optional arguments called `stdout` and `stderr`.

[Read the manual](https://docs.python.org/3.3/library/subprocess.html#subprocess.call).

**Comment by deavmi** [comment]
Oh I see now, kinda, Python doesn't send it to bash, the run command, therefore Bash syntax not working.
